name: Remove Labels
inputs:
  LABELS:
    description: The labels' name to be removed. Must be separated with line breaks if there're multiple labels.
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      env:
        LABELS: '${{inputs.LABELS}}'
      with:
        result-encoding: string
        script: |
          const labels = process.env.LABELS.trim().split('\n');
          for(const label of labels){
              try{
                  await github.rest.issues.removeLabel({
                      issue_number: context.issue.number,
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      name: label
                  })
              }catch(err){
                  console.log(`${label} not included`)
              }
          }
