name: 'check-reviews'
description: 'Common reviews'
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      env: 
        MAX_APPROVALS: ${{ inputs.MAX_APPROVALS }}
      with:
        result-encoding: string
        script: |
          
            const MAX_APPROVALS = process.env.MAX_APPROVALS;
            try{
                const { data : reviews } = await github.rest.pulls.listReviews({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: context.issue.number,
                });
                const approvingReviewers = reviews.filter(review => review.state === "APPROVED")
                if(!(approvingReviewers >=  MAX_APPROVALS)){
                    core.setFailed(`Error: Approvals required ${MAX_APPROVALS}`);
                }
                core.debug('Passed approvals');
            }catch(err){
                core.setFailed(`Error in checkReviews: ${err}`);  
            }