name: 'Automerge'
description: 'Common automerge'
inputs:
  MAX_APPROVALS:
    description: 'Max approvals PR'
    required: true
  METHOD:
    default: "squash"
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      env: 
        MAX_APPROVALS: ${{ inputs.MAX_APPROVALS }}
        METHOD: ${{ inputs.METHOD }}
      with:
        result-encoding: string
        script: |
          const script = require('./actions/automerge/index.js')
          await script({github, context, core})